config/routes.rb
Rails.application.routes.draw do
  resources :discussions do
  resources :replies
end
  get "about", to:"about#index", as: :about

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to:  "registrations#new"
  post "sign_up", to: "registrations#create"
  
  get "sign_in", to:  "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"


  root to: "discussions#index"
  # Defines the root path route ("/")
  # root "articles#index"
end
  

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :user
    has_many :replies, dependent: :destroy
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :set_discussion, only: %i[ show edit update destroy ]
  before_action :require_user_logged_in! , only: %i[ show ]
  # GET /discussions or /discussions.json
  
  def index
    @discussions = Discussion.all
  end

  # GET /discussions/1 or /discussions/1.json
  def show
    @discussions = Discussion.all

  end

  # GET /discussions/new
  
  def new
       @discussion = Discussion.new
  
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions or /discussions.json
  def create   
    @discussion = Discussion.new(discussion_params)
    @discussion["user_id"] = session[:user_id]
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to discussion_url(@discussion), notice: "Discussion was successfully created." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1 or /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to discussion_url(@discussion), notice: "Discussion was successfully updated." }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1 or /discussions/1.json
  def destroy
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url, notice: "Discussion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discussion_params
      params.require(:discussion).permit(:title, :content)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
    def discussion_author(discussion)
        session[:user_id] == discussion.user_id
        
    end

    def reply_author(reply)
        session[:user_id] == reply.user_id
    end
end

app/views/discussions/_discussion.html.erb
<div class="album py-5 bg-light" >
<div class="container">

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
      <div class="card shadow-sm">       
        <div class="card-body">
          <p class="card-text"> <%= discussion.title %> </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            <%= link_to discussion do%> 
              <button type="button"  class="btn btn-sm btn-outline-secondary", discussion >View</button>
              <%end%>
                     </div>
            <small class="text-muted"> Replies: <%= discussion.replies.count %>  </small>
          </div>
        </div>
      </div>
    </div>
  
    
  </div>
</div>
</div>
</div>

</div>
   

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>

  <% if discussion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div class="mb3">
    <%= form.submit%>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Show this discussion", @discussion %> |
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/index.html.erb
<h1>Discussions</h1>

<div id="discussions">
  <% @discussions.each do |discussion| %>
    <%= render discussion %>
  <% end %>
</div>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render "form", discussion: @discussion %>

<br>

<div>
  <%= link_to "Back to discussions", discussions_path %>
</div>

app/views/discussions/show.html.erb
<div id="<%= dom_id @discussion %>">
  <p class="text-break">
    <strong>Title:</strong>
    <%= @discussion.title %>
    <hr />

      <%= @discussion.content %>
  </p>
      <hr />
 
 <div class="btn-group">
 <%= link_to discussions_path do%> 
   <button type="button"  class="btn btn-sm btn-outline-secondary">Back to discussions</button>
   <%end%>
          </div>

<% if discussion_author(@discussion) %>

  <div class="mb3">
  
  <%= link_to edit_discussion_path(@discussion) do%> 
  <button type="button"  class="btn btn-sm btn-outline-secondary">Edit</button>
  <%end%>

  <hr />
  <%= button_to "Destroy this discussion", @discussion, method: :delete, class: "btn btn-primary" %>

</div>
<% end %>


</div>

    <h2 class="subtitle is-5 has-text-grey"> Replies</h2>

    <div id="discussion-replies">
      <%= render @discussion.replies %>
    </div>

    <hr />
     <%= render 'replies/form' %>